version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/frontend-client  # Chemin relatif depuis src/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend/frontend-client:/app
      - /app/node_modules
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
